[package]
name = "codemap"
version = "0.1.2"
authors = ["FreskyZ <fresky7@outlook.com>"]

[dependencies]
codepos = { path = "../codepos" }
messages = { path = "../messages" }

[lib]
name = "codemap"
path = "src/lib.rs"