[package]
name = "codemap"
version = "0.1.2"
authors = ["FreskyZ <fresky7@outlook.com>"]
workspace = "../ffc"

[dependencies]
util = { path = "../util" }

[lib]
name = "codemap"
path = "src/lib.rs"