[package]
name = "codemap"
version = "0.1.3"
authors = ["FreskyZ <FreskyZ@outlook.com>"]
edition = "2018"

[dependencies]
util = { path = "../util" }

[lib]
name = "codemap"
path = "src/lib.rs"
