#![allow(non_upper_case_globals)]
///! ---------------------------------------------------------------------------------
///! This code is auto generated by a tool $repo/scripts/diagnostics.py
///! Changes may cause incorrect behavior and will be lost if the code is regenerated.
///! ---------------------------------------------------------------------------------

pub const failed_to_read_for_module_request: &str = "failed to read all candidates for module request";
pub const originated_here: &str = "originated from here";
pub const unexpected_eof: &str = "unexpected end of file";
pub const unexpected_eol: &str = "unexpected end of line";
pub const block_comment_starts_here: &str = "block comment starts here";

macro_rules! failed_to_read_file { ($p1:expr, $p2:expr) => (format!("failed to read file {}: {}", $p1, $p2)) }
macro_rules! import_candidates { ($p1:expr) => (format!("candidates: {}", $p1)) }

pub(crate) use failed_to_read_file;
pub(crate) use import_candidates;
