[package]
name = "semantic"
version = "0.1.3"
authors = ["FreskyZ <FreskyZ@outlook.com>"]
edition = "2018"

[dependencies]
codemap = { path = "../codemap" }
util = { path = "../util" }
messages = { path = "../messages" }
lexical = { path = "../lexical" }
syntax = { path = "../syntax" }
