[package]
name = "semantic"
version = "0.1.2"
authors = ["FreskyZ <fresky7@outlook.com>"]
workspace = "../ffc"

[dependencies]
util = { path = "../util" }
codepos = { path = "../codepos" }
messages = { path = "../messages" }
lexical = { path = "../lexical" }
syntax = { path = "../syntax" }
