[package]
name = "semantic"
version = "0.1.3"
edition = "2021"

[dependencies]
codemap = { path = "../codemap" }
util = { path = "../util" }
messages = { path = "../messages" }
lexical = { path = "../lexical" }
syntax = { path = "../syntax" }
