[package]
name = "ffc"
version = "0.1.2"
authors = ["FreskyZ <fresky7@outlook.com>"]

[dependencies]
driver = { path = "../driver" }
util = { path="../util" }

[[bin]]
name = "ffc"
path = "main.rs"