[package]
name = "messages"
version = "0.1.3"
authors = ["FreskyZ <FreskyZ@outlook.com>"]
edition = "2018"

[dependencies]
codemap = { path = "../codemap"}
util = { path = "../util" }

[lib]
name = "messages"
path = "lib.rs"
