[package]
name = "lexical"
version = "0.1.3"
edition = "2021"

[dependencies]
util = { path = "../util" }
codemap = { path = "../codemap" }
messages = { path = "../messages" }

[features]
trace_num_lit_parse = []
trace_v2_parse = []
trace_char_lit_parse = []
