[package]
name = "ffc"
version = "0.1.1"
authors = ["FreskyZ <fresky7@outlook.com>"]

[dependencies]
new_lexical = { path = "../lexical" }
codemap = { path="../codemap" }
lexical_pos = { path="../lexical_pos" }
util = { path="../util" }

[[bin]]
path = "src/main.rs"
name = "ffc"